config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "partner", to: "pages#partner"
  get "mycard", to: "pages#mycard"

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'registrations' }

  resource :user do
    resources :perk_requests, only: [:index]
    post "perk_requests", to: 'perk_requests#mask_perk'
  end

  resources :perks, only: [:index, :show, :update]
  get "search_perks", to: "perks#search", as: :search_perks
  # resources :perk_usages, only: [:index, :show]

  resources :perks, only: [:index, :show, :update] do
    resources :perk_requests, only: [:show, :new, :create]
  end


  resources :businesses, only: [:index, :show, :new, :create]
end

app/models/perk_request.rb
class PerkRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :perk
end

app/controllers/perk_requests_controller.rb
class PerkRequestsController < ApplicationController
  before_action :find_perk, except: [:index, :mask_perk]

  def index
    @perk_requests = policy_scope(PerkRequest)
    @perk_requests = current_user.perk_requests.select do |perk_request|
     !perk_request.hidden
    end

  end

  def mask_perk
   perk_request = PerkRequest.find(params[:perk_request_id])
   authorize perk_request
   perk_request.hidden = true
   perk_request.save
   redirect_to user_perk_requests_path
  end


  def show
    @perk_request = @perk.perk_requests.find(params[:id])
    authorize @perk_request
  end

  def new
    @perk_request = PerkRequest.new
  end

  def create
    @perk_request = PerkRequest.new
    @perk_request.perk = @perk
    @perk_request.user = current_user
    authorize @perk_request
    if @perk_request.save
      redirect_to perk_perk_request_path(@perk, @perk_request)
      # redirect_to perk_usages_path
    else
      render 'perks/show'
    end
  end

  private

  def find_perk
    @perk = Perk.find(params[:perk_id])
  end
end

app/helpers/perk_request_helper.rb
module PerkRequestHelper
end

app/views/perk_requests/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 request-card">
      <div class="">
        <% @perk_requests.each do |perk_request| %>
        <div class="box-request">
          <div class="col-xs-4 col-xs-offset-1">

          </div>
          <div class="col-xs-7 pt-10 pl-5">
            <h2><%= perk_request.perk.title.upcase %></h4>
            <h4><%= perk_request.perk.business.name.capitalize %></h4>
            <p><i class="fa fa-tag"></i> <%=perk_request.perk.business.category.title.capitalize%></p>
            <%#=image_tag @business.picture.url(:medium), class: "img-circle" %>
          </div>
          <div class="button-delete">
          <%= link_to perk_requests_user_path(perk_request_id: perk_request.id), remote: true, method: :post do %>
            <i class="fa fa-minus-circle"></i>
            <% end %>
          </div>
        </div>
        <% end%>
      </div>
    </div>
  </div>
</div>


<%= content_for(:after_js) do %>
  <script>
  $( "button" ).click(function() {
    $( this ).parent().parent().parent().hide( "slow" );
  });
  </script>
<% end %>

app/views/perk_requests/show.html.erb
<div class="container">
  <div class="row">
    <div class="mt-30" id="container-recap">
      <div class="col-xs-12">
        <div class="box-recap">
          <div class="col-xs-4 col-xs-offset-1">
            <%= image_tag @perk.business.picture, class: "business-logo"%>
          </div>
          <div class="col-xs-7 pt-10 pl-5">
            <h2><%= @perk.title.upcase %></h4>
            <h4><%= @perk.business.name.capitalize %></h4>
            <p><i class="fa fa-tag"></i> <%=@perk.business.category.title.capitalize%></p>
          </div>
        </div>
      </div>

      <div class="col-xs-10 col-xs-offset-1">
        <h1>Pour bénéficier de ce bon plan :</h1>
        <div class="box-step">
          <p>1. Rendez vous au <%=@perk.business.address %></p>
          <%= link_to "Indique Moi L'itinéraire", "http://maps.google.com/maps", class: "btn btn-danger", id:"link-map", disabled: true, data: { locale: I18n.locale, destination: { latitude: @perk.business.latitude, longitude: @perk.business.longitude } }, :target => "_blank" %>
          <% content_for(:after_js) do %>
            <script type="text/javascript">setRoutePathFromLocation()</script>
          <% end %>
        </div>
      </div>
      <div class="col-xs-10 col-xs-offset-1">
        <div class="box-step">
          <p>2. Présentez votre carte de membre :)</p>
            <%= link_to "Accéder A Ma Carte", mycard_path, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>