config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "partner", to: "pages#partner"
  get "mycard", to: "pages#mycard"

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'registrations' }

  resource :user do
    resources :perk_requests, only: [:index]
    post "perk_requests", to: 'perk_requests#mask_perk'
  end

  resources :perks, only: [:index, :show, :update]
  get "search_perks", to: "perks#search", as: :search_perks
  # resources :perk_usages, only: [:index, :show]

  resources :perks, only: [:index, :show, :update] do
    resources :perk_requests, only: [:show, :new, :create]
  end


  resources :businesses, only: [:index, :show, :new, :create]
end

app/models/perk.rb
class Perk < ActiveRecord::Base
  belongs_to :business
  has_many   :perk_requests
  has_many   :perk_usages

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/


end

app/controllers/perks_controller.rb
class PerksController < ApplicationController
  def index
    skip_policy_scope
    @perks = Perk.all

    # @perks = perks.find(params[:business_id])
    # @perks_location = Perk.near(params[:city].capitalize, 20)
    # @markers = Gmaps4rails.build_markers(@perks) do |perk, marker|
    #   marker.lat perk.latitude
    #   marker.lng perk.longitude
  end

  def search
    @category = Category.find(params[:search_category_id]) # trouver la categorie où l'id correspend à la valeur récupérer via le filtre (search_category_id)
    @businesses = @category.businesses # pour faire la relation entre la category et les perks
    @perks = Perk.where(business: @businesses) # retourne les perks liés aux businesses de la category
    authorize @perks
  end

  def show
    @perk = Perk.find(params[:id])
    skip_authorization
  end

  def edit
    @perk = Perk.find(params[:id])
  end

  def update
     @perk = Perk.find(params[:id])
     @perk.state = true
     @perk.save
     authorize @perk
     redirect_to perks_path
     flash[:notice] = "Vous pouvez maintenant bénéficier de #{@perk.title}"
  end


  def perk_params
    params.require(:perk).permit(:title, :details, :state, :business_id, :picture)
  end

end

app/helpers/perks_helper.rb
module PerksHelper
end

app/views/perks/_map.html.erb
  <div id="map" style="width: 100%; height: 500px;">
    <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).on('ready', function() {
        handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      })
    <% end %>
  <% end %>
</div>

app/views/perks/_validation.html.erb
<div class="container">
  <div class="row text-center margin-top40">
    <div class="col-xs-6 col-xs-offset-3">
      <%= simple_form_for(@perk, url: perk_perk_requests_path(@perk, @perk_request), method: :post) do |f| %>
        <%= f.button :submit, value: "J'en profite !", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/perks/index.html.erb
<div id="wrapper-perks">
<div class="container-fluid">
  <div class="row text-center">
    <div class="btn-group">

        <%= form_tag search_perks_path, :method => 'get' do %>

          <p>
            <%= select_tag :search_category_id, options_from_collection_for_select(Category.all, :id, :title, params[:search_category_id]), class: 'select_picker' %>
            <%= submit_tag "Filtrer", style: "display:none" %>
          </p>
        <% end %>


      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 perk-card">
      <% @perks.each do |perk| %>
        <%= link_to perk_path(perk) do %>
          <div class="row relative bg-image-100" style="background-image: url(<%= image_url perk.picture %>); background-position: center center">
            <div class="row box-shadow-absolute">
              <p class="mt-5"><%= perk.business.name.upcase %></p>
              <div class="row box-color-absolute" style="background-image: url(<%= image_url "colorbar-inverse.png" %>); background-position: center center"></div>
               <div class="index-5 top-90">
                <p><%= perk.title.upcase %></p>
              </div>
              <div class="box-shadow-over"></div>
            </div>
          </div>
        <%end%>
      <%end%>
    </div>
    </div>
  </div>
</div>
<%= content_for(:after_js) do %>
  <script>
    $('.select_picker').selectpicker();
    $('select').change(function(e){
     $('form').submit()
    })
  </script>
<% end %>

app/views/perks/search.html.erb
<div id="wrapper-perks">
<div class="container-fluid">
  <div class="row text-center">
    <div class="btn-group">


        <%= form_tag search_perks_path, :method => 'get' do %>

          <%= select_tag :search_category_id, options_from_collection_for_select(Category.all, :id, :title, params[:search_category_id]), class: 'select_picker' %>
          <%= submit_tag "Filtrer", style: "display:none" %>
        <% end %>
          <!-- search_category_id : nouvelle donnée pour stocker le id récuperer via le filtre , dont (l'id) on passe à la methode search dans le perks_controller -->


    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 perk-card">
      <% @perks.each do |perk| %>
        <%= link_to perk_path(perk) do %>
          <div class="row relative bg-image-100" style="background-image: url(<%= image_url "Perk1.png" %>); background-position: center center">
            <div class="row box-shadow-absolute">
              <p class="mt-5"><%= perk.business.name.upcase %></p>
              <div class="row box-color-absolute" style="background-image: url(<%= image_url "colorbar-inverse.png" %>); background-position: center center"></div>
               <div class="index-5 top-90">
                <p><%= perk.title.upcase %></p>
              </div>
              <div class="box-shadow-over"></div>
            </div>
          </div>
        <%end%>
      <%end%>
    </div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    $('.select_picker').selectpicker();
    $('select').change(function(e){
     $('form').submit()
    })
  </script>
<% end %>

app/views/perks/show.html.erb
<div class="container-fluid">
  <div class="row text-center">
    <div class="col-xs-12 box-white-perk">
      <div class="perk-image" style="background-image: url(<%= image_url @perk.picture %>); background-position: center center">
        <div class="box-shadow-perk">
          <h2><%= @perk.business.name%></h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="box-color-perk" style="background-image: url(<%= image_url "colorbar.png" %>); background-position: center center">
        <h1><%= @perk.title %></h1>
      </div>
      <div class= "plr-10">
        <p><%= @perk.details %></p>
      </div>
      <div class= "col-xs-7 address_field">
        <i class="fa fa-map-marker"> <%= @perk.business.street %></i><br/>
        <i class="fa fa-tag"> <%= @perk.business.city %></i>
      </div>
      <div class= "col-xs-5 tel_field">
        <i class="fa fa-phone"> 0670282536<%= @perk.business.telephone %></i><br/>
        <i class="fa fa-check"> Tous les jours</i>
      </div>
    </div>
    <div class="row">
      <%= render 'validation'%>
    </div>
  </div>
</div>