config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "partner", to: "pages#partner"
  get "mycard", to: "pages#mycard"

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'registrations' }

  resource :user do
    resources :perk_requests, only: [:index]
    post "perk_requests", to: 'perk_requests#mask_perk'
  end

  resources :perks, only: [:index, :show, :update]
  get "search_perks", to: "perks#search", as: :search_perks
  # resources :perk_usages, only: [:index, :show]

  resources :perks, only: [:index, :show, :update] do
    resources :perk_requests, only: [:show, :new, :create]
  end


  resources :businesses, only: [:index, :show, :new, :create]
end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many     :perks
  belongs_to   :category
  geocoded_by  :address

  has_attached_file :picture,
    styles: { medium: "500x100>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  after_validation :geocode, if: :address_changed?


  def address_changed?
    :street_changed? || :zipcode_changed? || :city_changed?
  end

  def address
    "#{street}, #{zipcode} #{city}"
  end

  def gmaps4rails_infowindow
    "#{link_to 'Business', business_path}"
  end
end

app/models/business_label.rb
class BusinessLabel < ActiveRecord::Base
  belongs_to :business
  belongs_to :label
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :businesses
end

app/models/label.rb
class Label < ActiveRecord::Base
end

app/models/perk.rb
class Perk < ActiveRecord::Base
  belongs_to :business
  has_many   :perk_requests
  has_many   :perk_usages

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/


end

app/models/perk_request.rb
class PerkRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :perk
end

app/models/perk_usage.rb
class PerkUsage < ActiveRecord::Base
  belongs_to :user
  belongs_to :perk
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [ :facebook ]

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  has_many :perk_requests, dependent: :destroy
  has_many :perk_usages, dependent: :destroy

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.name = auth.info.name
      user.picture = process_uri(auth.info.image)
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  def self.process_uri(uri)
    require 'open-uri'
    require 'open_uri_redirections'
    open(uri, :allow_redirections => :safe) do |r|
      r.base_uri.to_s
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_layout
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!
  include Pundit

  protect_from_forgery with: :exception

  after_action :verify_authorized,    except: :index, unless: :devise_or_pages_or_admin_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_or_pages_or_admin_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def set_layout
    if devise_controller?
      self.class.layout "home"
    elsif admin_controller?
      return
    else
      self.class.layout "application"
    end
  end

  def admin_controller?
    controller_path.start_with?('admin/')
  end

  def devise_or_pages_or_admin_controller?
    devise_controller? || pages_controller? || admin_controller?
  end

  def pages_controller?
    controller_name == "pages"  # Brought by the `high_voltage` gem
  end

  def user_not_authorized
    flash[:error] = I18n.t('controllers.application.user_not_authorized', default: "You can't access this page.")
    redirect_to(root_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:sign_up) << :picture

    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :picture
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    skip_policy_scope
    @perks = Perk.all

    @businesses = Business.all
    # @businesses = Business.near(params[:address], 20)
    @markers = Gmaps4rails.build_markers(@businesses) do |business, marker|
      marker.lat business.latitude
      marker.lng business.longitude
      marker.infowindow render_to_string(partial: "/businesses/map_pop", locals: { business: business })
    end
    # @json = User.all.to_gmaps4rails do |business, marker|
    #   marker.infowindow render_to_string(:partial => "/businesses/my_template", :locals => { :object => business})
    #   marker.picture({
    #               :picture => "http://www.blankdots.com/img/github-32x32.png",
    #               :width   => 32,
    #               :height  => 32
    #              })
    #   marker.title   "i'm the title"
    #   marker.sidebar "i'm the sidebar"
    #   marker.json({ :id => business.id, :foo => "bar" })
    # end
  end

 # authorize @business for other actions

  def show
    @business = Business.find(params[:id])
    @markers = Gmaps4rails.build_markers(@business) do |business, marker|
      marker.lat business.latitude
      marker.lng business.longitude
    end
    skip_authorization
  end

  def new
    @business = Business.new
    skip_authorization
  end

  def create

  end

  def business_params
      params.require(:business).permit(:title, :description, :city, :zipcode, :street, :address, :latitude, :longitude)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    skip_authorization
    @perks = Perk.all
  end

  def about
  end

  def contact
  end

  def partner
  end

  def mycard
    skip_authorization
  end
end

app/controllers/perks_controller.rb
class PerksController < ApplicationController
  def index
    skip_policy_scope
    @perks = Perk.all

    # @perks = perks.find(params[:business_id])
    # @perks_location = Perk.near(params[:city].capitalize, 20)
    # @markers = Gmaps4rails.build_markers(@perks) do |perk, marker|
    #   marker.lat perk.latitude
    #   marker.lng perk.longitude
  end

  def search
    @category = Category.find(params[:search_category_id]) # trouver la categorie où l'id correspend à la valeur récupérer via le filtre (search_category_id)
    @businesses = @category.businesses # pour faire la relation entre la category et les perks
    @perks = Perk.where(business: @businesses) # retourne les perks liés aux businesses de la category
    authorize @perks
  end

  def show
    @perk = Perk.find(params[:id])
    skip_authorization
  end

  def edit
    @perk = Perk.find(params[:id])
  end

  def update
     @perk = Perk.find(params[:id])
     @perk.state = true
     @perk.save
     authorize @perk
     redirect_to perks_path
     flash[:notice] = "Vous pouvez maintenant bénéficier de #{@perk.title}"
  end


  def perk_params
    params.require(:perk).permit(:title, :details, :state, :business_id, :picture)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  def perk_params
    params.require(:user).permit(:first_name, :last_name, :email, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/perk_request_helper.rb
module PerkRequestHelper
end

app/helpers/perk_usages_helper.rb
module PerkUsagesHelper
end

app/helpers/perks_helper.rb
module PerksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='<%= "#{controller_path.gsub('/', '_')}_#{action_name}" + "_html" %>'>
<head>
  <title><%= yield(:title) || "Wagon Rails" %></title>
  <meta name="description" content="<%= (yield(:description) || "").squish %>">

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= "#{controller_path.gsub('/', '_')}_#{action_name}" %>">
  <%#= render "shared/navbar" %>
  <%= render "shared/sidebar" %>

  <nav class='nav-bar'>
    <label for="sidebar-checkbox" class="sidebar-toggle"></label>
    <a class="navbar-logo" href="/">
      <%= image_tag "logo.png" %>
    </a>
  </nav>
  <div class="img-width-100">
    <%= image_tag "barre_navbar.png"%>
  </div>
  <%= render "shared/flashes" %>

  <div class="wrap">
    <%= yield %>
  </div>

  <%= render "shared/footer" %>




  <%= javascript_include_tag "application" %>
  <script src="//maps.google.com/maps/api/js?sensor=false&key=AIzaSyCQy0aku9t76hUrsCr0VyMf1aZLCTqMbTU" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/trunk/geolocationmarker/src/geolocationmarker-compiled.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js">
  </script>

  <%#= javascript_include_tag :application %>
  <%= yield(:after_js) %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || "Wagon Rails" %></title>
  <meta name="description" content="<%= (yield(:description) || "").squish %>">

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="wrap">
    <%= yield %>
  </div>

  <script src="//maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
   <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

   <%= javascript_include_tag "application" %>

  <%#= javascript_include_tag :application %>
  <%= yield(:after_js) %>

</body>
</html>

app/views/pages/home.html.erb
<div id="wrapper">
  <div class="container-fluid h4-home h1-home">
    <div class="row text-center">
      <h4>LES BONS PLANS A L'AFFICHE</h4>
      <div class="col-xs-12 carrousel">
        <% @perks.each do |perk| %>
          <%= link_to perk_path(perk) do %>
              <div class="row relative box-white-home" >
                <div class="bg-image-235" style="background-image: url(<%= image_url perk.picture %>); background-position: center center"></div>
                <div class="row" id="box-shadow-home">
                  <p><%= perk.business.category.title%></p>
                </div>
                <div class="row" id="info-business">
                  <div class="col-xs-6" id="business-name">
                    <h1><%= perk.business.name.capitalize %></h1>
                  </div>
                  <div class="col-xs-6" id="business-city">
                    <i class="fa fa-map-marker"> <%= perk.business.city.capitalize %></i>
                  </div>
                </div>
                  <div class="row big-box-color-absolute" style="background-image: url(<%= image_url "colorbar.png" %>); background-position: center center">
                    <p><%= perk.title.upcase %></p>
                </div>
              </div>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/mycard.html.erb
<div id="wrapper">
  <div class="card relative">
    <%= image_tag (current_user.picture.exists? ? current_user.picture : "profile.png"), class: "img-circle", style: "margin:auto;"  %>

    <%= image_tag "macarte.png", class: "img-card", style: "margin:auto;"%>
    <h2><%= current_user.first_name%> <%= current_user.last_name%> <%= current_user.name%> </h2>
  </div>
</div>

app/views/pages/partner.html.erb
<div class="container">
  <div class="row text-center" id="partner">
    <h2>Devenez Partenaire</h2>
    <h3>Vous êtes un commerçant responsable ?</h3>
    <p>Inscrivez vous, c'est <strong>gratuit</strong> ! </br>
      Dès notre confirmation, votre commerce et ses bons plans seront visibles
      auprès de toute la communauté ! </p>
    <div class="col-xs-8 col-xs-offset-2">
      <div class="btn btn-danger f-size13 a-white">
        <%= link_to "Ajouter Mon Commerce", new_business_path %>
      </div>
    </div>
    <div class="row mt-30">
    </br>
      <h3>Vous êtes un consommateur responsable ?</h3>
      <p>Cette initiative vous parle et vous souhaiteriez y participer ? Devenez <strong>Ambassadeur</strong> !</br>
        Rejoignez le groupe qui rassemble qui rassemble toute la communauté </p>
      <div class="col-xs-8 col-xs-offset-2">
        <div class="btn btn-success f-size13 a-white">
          <%= link_to "Devenir Ambassadeur", new_business_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- <div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>
    </div>
  </div>
</div> -->

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container-fluid">
    <ul class='list-inline text-center'>
      <li>
        <%= link_to root_path do %>
          <%= image_tag "footer_icon.png" %>
          <p>Accueil</p>
        <% end %>
      </li>
      <li>
        <%= link_to edit_user_registration_path do %>
          <%= image_tag "footer_icon.png" %>
          <p>Mon Profil</p>
        <% end %>
      </li>
      <li>
        <%= link_to perks_path do %>
          <%= image_tag "footer_icon.png" %>
          <p>Bons Plans</p>
        <% end %>
      </li>
      <li>
        <%= link_to businesses_path do %>
          <%= image_tag "footer_icon.png" %>
          <p>Map</p>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-envelope-o"></i> <%= t(".messages", default: "Messages") %>
            <% end %>
          </li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <%= image_tag "http://placehold.it/30x30", class: "img-avatar" %>
              Profile <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-home"></i>  <%= t ".profile", default: "Flat" %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Sign out" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path %>
          </li>
          <li>
            <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path %>
          </li>
        <% end %>
        <li>
          <%= link_to t(".top_call_to_action", default: "Rent your flat"), "#", class: "btn" %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_sidebar.html.erb
<!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->
<div class="sidebar" id="sidebar">
  <div class="sidebar-item">


    <% if user_signed_in? %>
        <%= image_tag (current_user.picture.exists? ? current_user.picture : "profile.png"), class: "img-circle"  %>
        <p>
          <%= current_user.first_name %>
          <%= current_user.last_name %>
          <%= current_user.name %>
        </p>
    <% end %>
  </div>

  <nav class="sidebar-nav">
    <div class="sidebar-nav-item"><i class="fa fa-home"></i><%= link_to "Accueil", root_path %></div>
    <div class="sidebar-nav-item"><i class="fa fa-tag"></i><%= link_to "Bons Plans", perks_path %></div>
    <div class="sidebar-nav-item"><i class="fa fa-street-view"></i><%= link_to "Autour De Moi", businesses_path %></div>
    <div class="sidebar-nav-item"><i class="fa fa-cart-arrow-down"></i><%= link_to "Mon Panier", perk_requests_user_path %></div>
    <div class="sidebar-nav-item"><i class="fa fa-cog"></i><%= link_to "Paramètres", new_user_session_path %></div>
    <div class="sidebar-nav-item"><i class="fa fa-user-plus"></i><%= link_to "Devenir Partenaire", partner_path %></div>
    <div class="sidebar-nav-item"><i class="fa fa-info-circle"></i><%= link_to "A Propos", new_user_session_path %></div>
    <div class="sidebar-nav-item"><i class="fa fa-sign-out"></i><%= link_to destroy_user_session_path, method: :delete do %>
      <%= t ".sign_out", default: "Se Déconnecter" %>
    <% end %></div>
  </nav>

  <div class="sidebar-item">
    <p>
      © CFORFGOOD
    </p>
  </div>
</div>